---
- name: Install epel-elease
  yum: name=epel-release state=latest update_cache=yes

- name: Install mysql-community-release
  yum: name=http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm state=present

- name: get the indigo repository conf
  get_url: url={{ item.url }} dest={{ item.dest }}
  with_items:
    - { url: 'http://repo.indigo-datacloud.eu/repos/1/indigo1-testing-base.repo', dest: '/etc/yum.repos.d/indigo1-testing-base.repo' }
    - { url: 'http://repo.indigo-datacloud.eu/repos/1/indigo1-testing-third-party.repo', dest: '/etc/yum.repos.d/indigo1-testing-third-party.repo' }
    - { url: 'http://repo.indigo-datacloud.eu/repos/1/indigo1-testing-updates.repo', dest: '/etc/yum.repos.d/indigo1-testing-updates.repo' }

- name: Install necessary packages
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - compat-guile18
    - compat-guile18-devel
    - curl
    - dejavu-fonts-common
    - dejavu-sans-mono-fonts
    - flex-devel
    - gcc-c++
    - git
    - graphviz-devel
    - gsoap
    - gsoap-devel
    - gsl-devel
    - gsl
    - gtk2
    - gtk2-devel
    - guile-devel
    - hdf5-mpich
    - hdf5-mpich-devel
    - jansson
    - jansson-devel
    - libcurl-devel
    - libssh2-devel
    - libtool-ltdl
    - libtool-ltdl-devel
    - libxml2
    - libxml2-devel
    - mpich
    - mpich-autoload
    - mpich-devel
    - mysql-community-devel
    - MySQL-python
    - netcdf-mpich
    - netcdf-mpich-devel
    - openssl
    - openssl-devel
    - policycoreutils-python
    - readline
    - readline-devel
    - rrdtool
    - sudo
    - wget
    - indent
    - lcov
    - python-pip
    - httpd
    - php
    - mysql-community-server
    - munge
    - munge-devel
    - munge-libs

- name: 2nd set of packages slurm ophidia and libmatheval - the ones from the indigo repos
  yum: name={{ item }} state=latest update_cache=yes disable_gpg_check=yes
  with_items:
    - libmatheval
    - ophidia-analytics-framework
    - ophidia-primitives
    - ophidia-server
    - ophidia-terminal
    - slurm
    - slurm-munge
    - slurm-openlava
    - slurm-pam_slurm
    - slurm-perlapi
    - slurm-plugins
    - slurm-seff
    - slurm-sjobexit
    - slurm-sjstat
    - slurm-slurmdb-direct
    - slurm-slurmdbd
    - slurm-sql
    - slurm-torque

#- name: install slurm and ophidia rpms (TEMPORARY from non repo url)
#  yum: name={{ item }} state=present validate_certs=no
#  with_items:
#    - '{{ slurm_rpms }}slurm-16.05.2-1.el7.centos.x86_64.rpm'
#    - '{{ slurm_rpms }}slurm-munge-16.05.2-1.el7.centos.x86_64.rpm'
#    - '{{ slurm_rpms }}slurm-openlava-16.05.2-1.el7.centos.x86_64.rpm'
#    - '{{ slurm_rpms }}slurm-pam_slurm-16.05.2-1.el7.centos.x86_64.rpm'
#    - '{{ slurm_rpms }}slurm-perlapi-16.05.2-1.el7.centos.x86_64.rpm'
#    - '{{ slurm_rpms }}slurm-plugins-16.05.2-1.el7.centos.x86_64.rpm'
#    - '{{ slurm_rpms }}slurm-seff-16.05.2-1.el7.centos.x86_64.rpm'
#    - '{{ slurm_rpms }}slurm-sjobexit-16.05.2-1.el7.centos.x86_64.rpm'
#    - '{{ slurm_rpms }}slurm-sjstat-16.05.2-1.el7.centos.x86_64.rpm'
#    - '{{ slurm_rpms }}slurm-slurmdb-direct-16.05.2-1.el7.centos.x86_64.rpm'
#    - '{{ slurm_rpms }}slurm-slurmdbd-16.05.2-1.el7.centos.x86_64.rpm'
#    - '{{ slurm_rpms }}slurm-sql-16.05.2-1.el7.centos.x86_64.rpm'
#    - '{{ slurm_rpms }}slurm-torque-16.05.2-1.el7.centos.x86_64.rpm'
#    - '{{ slurm_rpms }}libmatheval-1.1.11-5.el7.centos.x86_64.rpm'
#    - '{{ oph_rpms }}ophidia-analytics-framework-0.10.2-0.el7.centos.x86_64.rpm'
#    - '{{ oph_rpms }}ophidia-primitives-0.10.2-0.el7.centos.x86_64.rpm'
#    - '{{ oph_rpms }}ophidia-server-0.10.2-0.el7.centos.x86_64.rpm'
#    - '{{ oph_rpms }}ophidia-terminal-0.10.2-0.el7.centos.x86_64.rpm'

- name: Create user for Ophidia framwork
  user: name={{ oph_user }} shell=/bin/bash generate_ssh_key=yes ssh_key_bits=2048

# Comment the get and unarchive of these tarballs since we now install rpms
# keep this task until proven that the rpms are doing their work on ophidia
#- name: Unarchive
#  unarchive: src={{ item }} dest=/usr/local owner=root group=root copy=no
#  with_items:
#    - http://ftp.gnu.org/gnu/libmatheval/libmatheval-1.1.11.tar.gz
#    - http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.17.tar.gz
#    - ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.4.0.tar.gz
#    - http://www.lip.pt/~david/gsoap_2.8.27.tgz

- name: Copy template of ophidia server server.conf
  template:
    src=server.conf.j2
    dest=/usr/local/ophidia/oph-server/etc/server.conf
    mode=0644
    owner=root
    group=root

- name: Copy template of slurm.conf
  template:
    src=slurm.conf.j2
    dest=/etc/slurm/slurm.conf
    mode=0644
    owner=root
    group=root

- name: Copy template of .my.cnf to ophi_user
  template:
    src=.my.cnf.j2
    dest=/home/{{ oph_user }}/.my.cnf
    mode=0600
    owner={{ oph_user }}
    group={{ oph_user }}

- name: Copy template of .my.cnf to root
  template:
    src=.my.cnf.j2
    dest=/root/.my.cnf
    mode=0600
    owner=root
    group=root

- name: ownership of /etc/munge
  file: path=/etc/munge owner=munge group=root

- name: Make munge private key
  shell: dd if=/dev/urandom bs=1 count=1024 > /etc/munge/munge.key
  become: true
  become_user: munge

- name: Set permissions on /etc/munge/munge.key
  file: path=/etc/munge/munge.key mode=400

- name: Creating root SSL cert
  command: >
    openssl req
      -newkey rsa:1024
      -passout pass:{{ cert_passwd }}
      -subj "/"
      -sha1
      -keyout rootkey.pem
      -out rootreq.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert/

- name: Sign root SSL cert
  command: >
    openssl x509
      -req
      -in rootreq.pem
      -passin pass:{{ cert_passwd }}
      -sha1
      -extensions v3_ca
      -signkey rootkey.pem
      -out rootcert.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert/

- name: merge cert and key of root cert
  shell: cat rootcert.pem rootkey.pem > cacert.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert/
    executable: /bin/bash

- name: Creating server SSL cert
  command: >
    openssl req
      -newkey rsa:1024
      -passout pass:{{ cert_passwd }}
      -subj "/"
      -sha1
      -keyout serverkey.pem
      -out serverreq.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert/

- name: Sign server SSL cert
  command: >
    openssl x509
      -req
      -in serverreq.pem
      -passin pass:{{ cert_passwd }}
      -sha1
      -extensions usr_cert
      -CA cacert.pem
      -CAkey cacert.pem
      -CAcreateserial
      -out servercert.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert/

- name: merge cert and key of server cert
  shell: cat servercert.pem serverkey.pem rootcert.pem > myserver.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert/
    executable: /bin/bash

- name: Remove intermediate certs
  file: path={{ item }} state=absent
  with_items:
    - /usr/local/ophidia/oph-server/etc/cert/rootcert.pem
    - /usr/local/ophidia/oph-server/etc/cert/rootkey.pem
    - /usr/local/ophidia/oph-server/etc/cert/rootreq.pem
    - /usr/local/ophidia/oph-server/etc/cert/servercert.pem
    - /usr/local/ophidia/oph-server/etc/cert/serverkey.pem
    - /usr/local/ophidia/oph-server/etc/cert/serverreq.pem
    - /usr/local/ophidia/oph-server/etc/cert/cacert.srl

#####
# TODO: for now the service will have to be started manually
# will have to figure out the problems of centos7 systemd
- name: ownership mysql for /var/log/mysqld.log
  file: path=/var/log/mysqld.log owner=mysql group=mysql

- name: mysql prepare system tables
  command: /usr/bin/mysql-systemd-start pre
  become: true
  become_user: mysql

- name: Start mysql_safe
  shell: /usr/bin/mysqld_safe --user=mysql 2>&1 > /dev/null &
  args:
    executable: /bin/bash

- name: start munged
  command: /usr/sbin/munged
  become: true
  become_user: munge

- name: start slurmd
  command: /usr/sbin/slurmd

- name: start slurmctld
  command: /usr/sbin/slurmctld

- name: start httpd
  command: /usr/sbin/httpd

####

- name: set the mysql root user passwd
  mysql_user: name=root password={{ cert_passwd }}

- name: create ophidia databases
  mysql_db: name={{ item }} state=present
  with_items:
    - ophidiadb
    - oph_dimensions

- name: import ophidia analytics db
  mysql_db: name=ophidiadb state=import target=/usr/local/ophidia/oph-cluster/oph-analytics-framework/etc/ophidiadb.sql

- name: Copy template of .my.cnf to root
  template:
    src=ophdb-host.sql.j2
    dest=/tmp/ophdb-host.sql
    mode=0600
    owner=root
    group=root

- name: import ophdb-host.sql
  mysql_db: name=ophidiadb state=import target=/tmp/ophdb-host.sql

- name: Start ophidia server
  shell: /usr/local/ophidia/oph-server/bin/oph_server -d 2>&1 > /dev/null &
  args:
    executable: /bin/bash

