---
- name: Install epel-elease
  yum: name=epel-release state=latest update_cache=yes

- name: Install mysql-community-release
  yum: name=http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm state=present

- name: get the indigo repository conf
  get_url: url={{ item.url }} dest={{ item.dest }}
  with_items:
    - { url: 'http://repo.indigo-datacloud.eu/repos/1/indigo1-testing-base.repo', dest: '/etc/yum.repos.d/indigo1-testing-base.repo' }
    - { url: 'http://repo.indigo-datacloud.eu/repos/1/indigo1-testing-third-party.repo', dest: '/etc/yum.repos.d/indigo1-testing-third-party.repo' }
    - { url: 'http://repo.indigo-datacloud.eu/repos/1/indigo1-testing-updates.repo', dest: '/etc/yum.repos.d/indigo1-testing-updates.repo' }

- name: Install necessary packages
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - git
    - gcc-c++
    - curl
    - flex-devel
    - compat-guile18
    - compat-guile18-devel
    - guile-devel
    - graphviz-devel
    - gsl-devel
    - gsl
    - gtk2
    - gtk2-devel
    - jansson
    - jansson-devel
    - libcurl-devel
    - libssh2-devel
    - libtool-ltdl
    - libtool-ltdl-devel
    - libxml2
    - libxml2-devel
    - mpich
    - mpich-devel
    - mysql-community-devel
    - openssl
    - openssl-devel
    - policycoreutils-python
    - readline
    - readline-devel
    - sudo
    - wget
    - indent
    - lcov
    - python-pip
    - httpd
    - php
    - mysql-community-server
    - munge
    - munge-devel
    - munge-libs

- name: install slurm and ophidia rpms (TEMPORARY from non repo url)
  yum: name={{ item }} state=present validate_certs=no
  with_items:
    - '{{ slurm_rpms }}slurm-16.05.2-1.el7.centos.x86_64.rpm'
    - '{{ slurm_rpms }}slurm-munge-16.05.2-1.el7.centos.x86_64.rpm'
    - '{{ slurm_rpms }}slurm-openlava-16.05.2-1.el7.centos.x86_64.rpm'
    - '{{ slurm_rpms }}slurm-pam_slurm-16.05.2-1.el7.centos.x86_64.rpm'
    - '{{ slurm_rpms }}slurm-perlapi-16.05.2-1.el7.centos.x86_64.rpm'
    - '{{ slurm_rpms }}slurm-plugins-16.05.2-1.el7.centos.x86_64.rpm'
    - '{{ slurm_rpms }}slurm-seff-16.05.2-1.el7.centos.x86_64.rpm'
    - '{{ slurm_rpms }}slurm-sjobexit-16.05.2-1.el7.centos.x86_64.rpm'
    - '{{ slurm_rpms }}slurm-sjstat-16.05.2-1.el7.centos.x86_64.rpm'
    - '{{ slurm_rpms }}slurm-slurmdb-direct-16.05.2-1.el7.centos.x86_64.rpm'
    - '{{ slurm_rpms }}slurm-slurmdbd-16.05.2-1.el7.centos.x86_64.rpm'
    - '{{ slurm_rpms }}slurm-sql-16.05.2-1.el7.centos.x86_64.rpm'
    - '{{ slurm_rpms }}slurm-torque-16.05.2-1.el7.centos.x86_64.rpm'
    - '{{ oph_rpms }}ophidia-analytics-framework-0.10.2-0.el7.centos.x86_64.rpm'
    - '{{ oph_rpms }}ophidia-primitives-0.10.2-0.el7.centos.x86_64.rpm'
    - '{{ oph_rpms }}ophidia-server-0.10.2-0.el7.centos.x86_64.rpm'
    - '{{ oph_rpms }}ophidia-terminal-0.10.2-0.el7.centos.x86_64.rpm'

- name: Copy template of ophidia server server.conf
  template:
    src=server.conf.j2
    dest=/usr/local/ophidia/oph-server/etc/server.conf
    mode=0644
    owner=root
    group=root

- name: Creating root SSL cert
  command: >
    openssl req
      -newkey rsa:1024
      -passout pass:abcd
      -subj "/"
      -sha1
      -keyout rootkey.pem
      -out rootreq.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert/
